### ISSUE TITLE
Style issues

### ISSUE THREAD

**Issue by TrejoCode** [scriptex/react-round-carousel#163]
![image](https://user-images.githubusercontent.com/16879799/191101397-d1aab354-2b63-4054-9679-c5a203c2432b.png)

Using Tailwinds

```
<div className="w-full h-full">
 <Carousel items={items} />
</div>

**Comment by scriptex** [comment]
It looks like you didn't include the built-in style. Please take a look at the provided example or directly use the `index.css` file located in the `src` folder.
Depending on your build process, you might need to import it in your JS or CSS entrypoint:
```js
import 'react-round-carousel/src/index.css';
```

or 

```css
@import 'react-round-carousel/src/index.css';
```

Let me know if I can help with anything else.
