### ISSUE TITLE
Not able to run the Carousel

### ISSUE THREAD

**Issue by anjali58** [scriptex/react-round-carousel#219]
```
        <div style={{width:400, height:200}}>
             <Carousel items={items} />
        </div>
```
under index.tsx
-> import 'react-round-carousel/src/index.css';
added above line

Can you please help me, I don't know what i'm missing but I'm getting blank screen and getting error of forwardRef @scriptex

**Comment by scriptex** [comment]
Hey, can you please provide more details? Which version are you using, what’s exactly the error, also a screenshot of the dev tools in your browser. Thanks!

**Comment by anjali58** [comment]
I'm using `react: 16.12.0`
this is the error i'm getting under dev tools
<img width="505" alt="Screenshot 2023-08-14 at 9 30 56 AM" []([](src="https://github.com/scriptex/react-round-carousel/assets/31721619/17f63d7a-066d-4517-b5f1-00f7b7aacc65">))

**Comment by scriptex** [comment]
@anjali58 I've installed the same version of React and I am not able to see this error....
Can you please provide me with a link to a repo where I can reproduce this?
If possible please set up a minimal reproducible example. 
Thanks!

**Comment by scriptex** [comment]
Also, in your screenshot above you didn't actually show the error but only where it originated. Can you paste the error as well?

**Comment by scriptex** [comment]
Hey, @anjali58, I will close the issue due to inactivity and I will assume that you have resolved it. Please re-open if needed.
